# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LiWuShuo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiWuShuo

  target 'LiWuShuoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiWuShuoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod “MJRefresh”
pod “YYModel”
pod “AFNetworking”
pod “SDWebImage”
pod “SDCycleScrollView”
pod “FMDB”
pod “FDFullscreenPopGesture”


end
